# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'IQKeyboardManager'

target 'linkuslight' do
    
    pod 'MJRefresh'

end

target 'linkuslightTests' do

end

target 'linkuslightUITests' do

end

