# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'IQKeyboardManager'

target 'linkuslight' do
    
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '7.0'
	pod 'AFNetworking', '~> 2.5'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Canvas', '~> 0.1.2'
    pod 'YYCache', '~> 1.0.4'
    
end

target 'linkuslightTests' do

end

target 'linkuslightUITests' do

end

